equinor/fusion-project-portal

client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx
client/packages/portal-ui/src/lib/portal-menu/group/ColorTab.tsx
client/packages/portal-ui/src/lib/portal-menu/styles.ts

Small tweak to padding on appgroup. 
Added borderradius to colortab to align better with figma design

fix: :bug: Added padding to appgroup and border styling to colortab

---

backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/MetricsController.cs

Radix automatically polls /metrics endpoint for health checks. This endpoint is not set up, thus resulting in a lot of 404 errors in Application Insights.
Solution: For now, implement a basic endpoint that returns OK. Later we can consider adding custom metrics.

feat: added /metrics controller endpoint used for Radix

---

client/packages/portal-client/src/components/context/HasContext.tsx
client/packages/portal-client/src/components/portal-frame/PortalFrame.tsx
client/packages/portal-core/src/framework-configurator/portal-context-configurators.ts
client/packages/portal-core/src/hooks/use-context-resolver.ts
client/packages/portal-core/src/hooks/use-onboarded-contexts.ts
client/packages/portal-core/tsconfig.json
client/packages/portal-pages/src/pages/project-page/ProjectPage.tsx

When selecting context that is not activate one will be navigated to root.

fix: fixing context navigation when context is not onboarded

---

.changeset/pr-401-1549632337.md
.github/workflows/common-changeset-pr.yml

Update GitHub action to not run on draft mode
Changeset action will now only run review not draft

chore: only run changeset action on review not draft

---

.changeset/pr-400-1549618563.md
client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx
client/packages/portal-core/src/queries/portal/getAppGroups.ts
client/packages/portal-ui/src/info-message/InfoMessage.tsx

In order to utilize any application within the project portal, the user must now select an activated context.

fix: enforce context selection to display application list in menu

---

.changeset/pr-406-1560342669.md
.github/workflows/common-changeset-pr.yml

The get changeset  workflow should not be triggered on the release branch
The get changeset  workflow should not be triggered on the release branch

fix: get changeset not running on release branch

---

.changeset/pr-420-1574233486.md
client/packages/portal-client/src/lib/portal-framework-config.tsx

Fixing auth issue on legacy application. #419
Fixing auth issue on legacy application, by providing fusion clientId #419

fix: legacy auth issue by providing fusion client id

---

.changeset/pr-425-1576203123.md
client/packages/portal-client/src/portal.config.json
client/packages/portal-core/src/app/utils/app-get-legacy-client-config.ts

fusionLegacyEnvIdentifier should always be returned in capital letters , some application check this and are case sensitive
fusionLegacyEnvIdentifier should always be returned in capital letters , some application check this and are case sensitive

fix: fusionLegacyEnvIdentifier  in capital letters

---

.changeset/pr-459-1602485654.md
client/packages/service-message/components/ServiceMessage.tsx
client/packages/service-message/components/ServiceMessageIcon.tsx

Implemented display of a legend for service message types in the side sheet.
Now display a legend for service message types in the side sheet.

feat: add legend for service message types in side sheet

---

.changeset/pr-470-1610845089.md
client/packages/service-message/components/NotificationService.tsx

Users now receive notifications only when the "notify user" option is explicitly set on a service message item. 
The notification system has been refined to ensure users receive notifications selectively. Now, notifications will be triggered only when the "notify user" option is explicitly set on a service message item.

feat: filter service messages by notify user flag

---

.changeset/pr-486-1632373097.md
client/packages/components/src/components/notifications/components/NotificationDateDivision.tsx
client/packages/components/src/components/notifications/components/Notifications.tsx
client/tsconfig.base.json

added no content message to notifications
When the user doesn't have any notifications, they will see a message indicating that there is no notification available.

chore: add no content to notifications

---

.changeset/pr-600-1771708999.md
client/packages/core/src/user/hooks/index.ts
client/packages/core/src/user/hooks/useUserContexts.ts
client/packages/portal-client/src/lib/portal-framework-config.tsx
client/packages/portal-pages/src/pages/project-portal-page/ProjectPortalPage.tsx

Project prediction on landing page

feat: project-predictions

---

.changeset/pr-637-1857569361.md
backend/src/Equinor.ProjectExecutionPortal.WebApi/Program.cs
clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Program.cs
clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/appsettings.json

Msal token failed after a while, changing to deafult token after advice from fusion core.
Change from msal to default token

fix: Use default token for fusion integration

---

.changeset/pr-680-2005667888.md
clientBackend.Dockerfile
radixconfig.yaml

The build is failing in radix. buildKit and buildCache are required. 
Updating radixconfig with  useBuildKit and useBuildCache

feat: use buildKit and buildCache in radix

---

.changeset/pr-687-2008126638.md
client/packages/portal-core/src/context-selector/ContextSelector.tsx

Now, when selecting the search-field,  all text highlighted in the same way as we are used to in browsers.
Now, when selecting context  all text highlighted in the same way as we are used to in browsers.

fix: Highlight all text when selecting breadcrumb search field

---

.changeset/pr-691-2014284277.md
client/packages/components/src/components/app-card/components/PinButton/index.tsx

The menu was closing when selecting a favorite, this is now fixed and the menu is still open.
Menu not closing when selecting a favorite.

fix: menu not closing when selecting favorite

---

.changeset/pr-689-2008366405.md
client/packages/portal-client/src/lib/feature-logger.ts

The fusion feature logger will now not log when no context is selected.
The fusion feature logger will now not log when no context is selected.

fix: Project portal logging empty object for context change to Fusion features endpoint

---

.changeset/pr-702-2020907790.md
backend/src/Equinor.ProjectExecutionPortal.Application/Commands/OnboardedApps/OnboardApp/OnboardAppCommand.cs
backend/src/Equinor.ProjectExecutionPortal.Application/Commands/OnboardedApps/UpdateOnboardedApp/UpdateOnboardedAppCommand.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/OnboardedAppController.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/OnboardedApp/ApiUpdateOnboardedAppRequest.cs
backend/src/tests/Equinor.ProjectExecutionPortal.Tests.WebApi/IntegrationTests/OnboardedAppControllerTests.cs

Context types can be added in OnboardedApp PUT endpoint

feat: add context-types to put endpoint

---

.changeset/pr-712-2027113298.md
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/OnboardedApp/ApiOnboardedApp.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/Portal/ApiPortal.cs

Add context-types as array of string.
ContextTypes are returned as array of string

feat: add context-types as array of string

---

.changeset/pr-747-2073460455.md
.github/workflows/common-release.yml
.github/workflows/deploy-apps-test.yml
client/apps/portal-administration/package.json
client/package.json
clientBackend.Dockerfile

apps are now on separate build pipeline

fix: build-fix

---

.changeset/pr-751-2076327141.md
backend/src/Equinor.ProjectExecutionPortal.Application/Commands/Portals/RemoveGlobalAppFromPortal/RemoveAppFromPortalCommand.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/PortalController.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/PortalApp/ApiRemovePortalAppRequest.cs
backend/src/tests/Equinor.ProjectExecutionPortal.Tests.WebApi/IntegrationTests/PortalControllerTests.cs

The Remove app endpoint now removes an app from a portal even if the app is contextual or global.
Delete app now removes an app from a portal even if the app is contextual or global

change remove-global-app to be remove-app

---

.changeset/pr-796-2093375130.md
client/apps/portal-administration/src/components/PortalApps/ActionBar.tsx
client/apps/portal-administration/src/context/RouterContext.tsx
client/apps/portal-administration/src/context/actions/router-actions.ts
client/apps/portal-administration/src/context/actions/updarte-route-router-action.test.ts
client/apps/portal-administration/src/context/actions/update-route-field-router-action.test.ts

fixing the route creation in the portal admin app
fixing the route creation in the portal admin app

fix:  add new route not adding double routes in pa app

---

.changeset/pr-812-2107152275.md
client/apps/portal-administration/package.json
client/packages/components/src/components/help/Help.tsx
client/packages/components/src/components/help/HelpMenu.tsx

Add link to CC App sharepoint site in the Help section
Add link to CC App sharepoint site in the Help section

feat: Add link to CC App sharepoint site in the Help section

---

.changeset/pr-808-2100756531.md
client/package.json
client/packages/components/src/components/my-roles-tab/hooks/use-update-my-roles-query.ts
client/packages/portal-pages/src/pages/project-page/components/milestones/LoadingSection.tsx
client/packages/portal-pages/src/pages/project-page/components/milestones/Milestones.tsx
client/packages/portal-pages/src/pages/project-page/components/milestones/use-presence-query.ts
client/packages/portal-pages/src/pages/sheared/components/data-info/DataInfo.tsx
client/yarn.lock

Fix errors and add data owner on milestones

chore: fix errors and add data owner on milestones

---

.changeset/pr-841-2151009734.md
client/apps/portal-administration/app.config.ts
client/apps/portal-administration/package.json
client/apps/portal-administration/src/components/PortalApps/PortalAppTable.tsx
client/apps/portal-administration/src/config.ts
client/apps/portal-administration/yarn.lock

- Admin app use new app manifest model
- Update all fusion packages in admin app

feat: admin app use new app manifest model

---

.changeset/pr-844-2153430938.md
backend/src/Equinor.ProjectExecutionPortal.Domain/Entities/OnboardedApp.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/PortalApp/ApiAddContextAppToPortalRequest.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/PortalApp/ApiAddGlobalAppToPortalRequest.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/PortalApp/ApiPortalApp.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/PortalApp/ApiPortalOnboardedApp.cs
backend/src/tests/Equinor.ProjectExecutionPortal.Tests.WebApi/IntegrationTests/AssertHelpers.cs
backend/src/tests/Equinor.ProjectExecutionPortal.Tests.WebApi/IntegrationTests/PortalControllerTests.cs

Rename two API models with the following changes:
- ApiPortalApp: **Key** is now **AppKey**
- ApiPortalOnboardedApp: **Key** is now **AppKey**
Renames Key to AppKey in ApiPortallApp and ApiPortalOnboardedApp models

change: API: rename Key to AppKey

---

.changeset/pr-862-2174620281.md
client/apps/portal-administration/src/components/Actions/ActivateSelectedWithContextButton.tsx
client/apps/portal-administration/src/components/PortalApps/ContextAppSideSheet.tsx
client/apps/portal-administration/src/query/apps-mutations.ts
client/apps/portal-administration/src/query/apps-queries.ts
client/apps/portal-administration/src/types/index.ts

…ts and queries
Align portal administration application with the new app management models
Align portal administration application with the new app management models

refactor: Align portal administration application with the new app management models

---

clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Program.cs

Removes response caching because we want immediate proxy data from Fusion
Removes response caching because we want immediate proxy data from Fusion

feat: Disable response caching

---

.changeset/pr-897-2237253494.md
backend/src/Equinor.ProjectExecutionPortal.Application/Queries/OnboardedApps/OnboardedAppDto.cs
backend/src/Equinor.ProjectExecutionPortal.Application/Services/AppService/AppService.cs
backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/OnboardedApp/ApiOnboardedApp.cs

Added a new field about whether an app is found in Fusion or not.
Field name: DoesNotExistInFusion (bool)
Upon resolving app, this field will be set conditionally
- OnboardedApp: Added a new field about whether an app is found in Fusion or not.

feat: Add information about whether an app is found in Fusion
