equinor/fusion-project-portal

.github/workflows/createDocs.yml
added -f to git add docs
Completes: AB#FILL_IN_YOUR_ISSUE_ID
=> fix(.github): added -f to git add docs

documentation/src/.vuepress/config.ts, documentation/src/projectPortalStudy/Readme.md
A study of what and how project portal will be developed and more 
Completes: [AB#32545](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/32545)
=> doc(documentation): Project Portal Study 

client/.editorconfig, client/.gitignore, client/.prettierignore, client/.prettierrc, client/.vscode/extensions.json, client/README.md, client/nx.json, client/package-lock.json, client/package.json, client/tools/tsconfig.tools.json, client/tsconfig.base.json
initial commit for client application setting up nx workspace 
Completes: [AB#31049](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/31049)
=> initial nx workspace setup

client/package.json, client/packages/portal-client/vite.config.ts, client/tsconfig.base.json, client/yarn.lock
Completes: AB#FILL_IN_YOUR_ISSUE_ID
=> chore: :wrench: vite read import paths from tsconfig

client/packages/portal-client/src/components/portal-header/Header.tsx, client/packages/portal-core/src/avatar/TopBarAvatar.tsx, client/packages/portal-core/src/avatar/index.ts, client/packages/portal-core/src/avatar/parsePresenceStatus.tsx, client/packages/portal-core/src/avatar/presence-observable.ts, client/packages/portal-core/src/avatar/top-bar-avatar.styles.ts, client/packages/portal-core/src/avatar/types.ts, client/packages/portal-core/src/index.ts
Completes: AB#FILL_IN_YOUR_ISSUE_ID
=> feat: :sparkles: top bar avatar with presence

client/packages/portal-core/src/phases/phases.ts, client/packages/portal-utils/src/rxjs/index.ts, client/packages/portal-utils/src/rxjs/observable-storage.ts
Completes: AB#FILL_IN_YOUR_ISSUE_ID
=> refactor: :recycle: observable storage rxjs

.github/pull_request_template.md, .github/workflows/defDone.yml, dod.yaml
This PR introduces a new Action which verifies that the Definition of Done Checklist exists in the Description of the PR, and will fail until all tasks are checked.
Completes: [AB#33717](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33717)
=> Action: Definition of Done

.github/workflows/ab-wi-validation.yml
Adds an Action validating a valid Azure Board Story ID.
Completes: [AB#32372](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/32372)
=> Action: validate the workitem reference

.github/workflows/check-commit-message.yml
on pr to main we the commit message need to be according to conventional commit
Completes: [AB#33722](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33722)
=> feat: ✨check conventional commit message

.github/workflows/sizeLabeler.yml
We had two actions with the same name - I renamed appropriatly the size-labeler.
Addresses: [AB#33767](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33767)
=> fix: Changed name of action

backend/src/Equinor.ProjectExecutionPortal.Application/Queries/WorkSurface/GetWorkSurfaceApps/GetWorkSurfaceAppGroupsWithAppsQuery.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/WorkSurfaceController.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/WorkSurfaceApp/ApiWorkSurfaceApp.cs
Implemented API endpoints for listing app groups and applications for a specific work surface and context.
If no context is supplied, all global apps should be listed. If context is supplied, both global and context app should be listed.
Integration test coverage is a work in progress and these endpoints will be covered later on.
Addresses: [AB#33724](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/33724)
=> feat: ✨ implement /apps endpoints for WorkSurface and context

client/packages/portal-client/src/components/app-module-loader/AppModuleLoader.tsx, client/packages/portal-core/src/framework-config/portal-framework-config.tsx, client/packages/portal-core/src/framework-configurator/portal-context-configurators.ts
Only navigate if user land on root 
Addresses: [AB#34171](https://statoil-proview.visualstudio.com/9949ad5e-7d15-4531-901e-296574079ee1/_workitems/edit/34171)
=> fix: only navigate on root

client/packages/portal-client/index.html
Addresses: AB#FILL_IN_YOUR_ISSUE_ID
=> feat: support react cdn

client/package.json, client/packages/portal-client/vite.config.ts, client/yarn.lock
Addresses: AB#FILL_IN_YOUR_ISSUE_ID
=> chore: add process env

client/package.json, client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx, client/packages/portal-client/src/components/portal-router/PortalRouter.tsx, client/packages/portal-client/src/framework-config/portal-framework-config.tsx, client/yarn.lock
Adding Fusion Navigation Module
=> feat: 107 add fusion navigation module to portal

backend/src/Equinor.ProjectExecutionPortal.WebApi/appsettings.json
=> chore: update fusion endpoint prefix

client/packages/portal-ui/src/lib/task/work-assigned/WorkAssigned.tsx
=> chore: remove some KPIs from task

backend/src/Equinor.ProjectExecutionPortal.WebApi/Program.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/appsettings.json, clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Program.cs
=> chore: Add AI to API

client/packages/portal-client/index.html
Addresses: AB#FILL_IN_YOUR_ISSUE_ID
=> fix: remove react cdn

backend/src/Equinor.ProjectExecutionPortal.Application/Cache/CacheDuration.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Cache/CacheManager.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Cache/FusionAppsCache.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Cache/ICacheManager.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Cache/IFusionAppsCache.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Commands/OnboardedApps/OnboardApp/OnboardAppCommand.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Services/AppService/AppService.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Services/AppService/IAppService.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/Constants.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/DiModules/ApplicationModule.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/DiModules/CacheModule.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/Program.cs
Adds in-mem caching for fetching Fusion Apps. Cache expiry is set to 1hr.
Addresses: #137
=> Feat: Implement caching for Fusion apps

backend/src/Equinor.ProjectExecutionPortal.Application/Queries/WorkSurface/GetWorkSurfaceAppGroupsWithApps/GetWorkSurfaceAppGroupsWithAppsQuery.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Queries/WorkSurface/WorkSurfaceAppDto.cs
Apps should be ordered on all queries
Addresses: No issue created
=> Chore: Ensure order by App within appGroup

client/packages/portal-ui/src/lib/header/HeaderContextSelector.tsx
navigate on context select in header if context is not present in url
=> fix: navigate on context select in header if context is not present in url

client/packages/portal-ui/src/lib/task/work-assigned/Tasks.tsx, client/packages/portal-ui/src/lib/task/work-assigned/WorkAssigned.tsx
=> fix: adding custom height for my work assigned and fixed group if undefined

client/.vscode/settings.json, client/packages/portal-ui/src/lib/task/work-assigned/Tasks.tsx, client/packages/portal-ui/src/lib/task/work-assigned/types/fusion-task.ts
=> fix: grouptask undefined and add key prop

client/packages/portal-ui/src/lib/header/Logo.tsx
=> fix: add cursor pointer on portal logo

client/packages/portal-client/index.html, client/packages/portal-core/src/context-selector/PortalContextSelector.tsx, client/packages/portal-core/src/framework-configurator/app-configurator.ts, client/packages/portal-pages/src/pages/project-page/ProjectPage.Styles.ts, client/packages/portal-pages/src/pages/project-page/ProjectPage.tsx, client/packages/portal-pages/src/pages/project-page/components/favorites/Favorites.tsx, client/packages/portal-pages/src/pages/view-page/ViewPage.Styles.ts, client/packages/portal-pages/src/pages/view-page/ViewPageHeader.tsx, client/packages/portal-ui/src/lib/header/HeaderStyles.ts, client/packages/portal-ui/src/lib/header/Logo.tsx, client/packages/portal-ui/src/lib/portal-menu/app-card/AppCard.tsx
=> feat: favorites on project page

radixconfig.yaml
=> fix: add ag grid to test env in radix config

client/packages/portal-client/src/customElementsDefinePolyfill.ts, client/packages/portal-client/src/main.tsx
Polyfill for displaying old fusion apps
=> fix: add _customElementsDefine poly fill for old fusion apps using web components

client/packages/portal-client/src/framework-config/portal-framework-config.tsx
=> fix: ag grid check on lisen key when adding ag grid lisens

clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Views/Shared/_Layout.cshtml
there should only be one man tag on page and this is used for content / app so this should be removed.
and there are some style issues when loading some app this might helt with that too..
=> fix: remove main tag

client/packages/portal-client/src/framework-config/portal-framework-config.tsx, client/packages/portal-client/src/portal.config.json, client/packages/portal-core/src/types/portal-config.ts
=> fix: use served bookmark config

backend/src/Equinor.ProjectExecutionPortal.Application/Queries/WorkSurface/GetWorkSurfaceAppGroupsWithContextAndGlobalApps/GetWorkSurfaceAppGroupsWithContextAndGlobalAppsQuery.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Services/WorkSurfaceService/WorkSurfaceService.cs
=> fix: fixed a bug where app duplicates would be returned in apps endpoint

radixconfig.yaml
Removed identity config from radix as it is unused (federated credentials)
=> chore: removed unused identity config from radix

client/packages/portal-ui/src/lib/header/breadcrumbs/AppBreadcrumb.tsx, client/packages/portal-ui/src/lib/header/breadcrumbs/styles.ts
top bar application is clickable but has no indication that its clickable
=> chore: top bar application is clickable but has no indication that its clickable

client/packages/portal-core/src/app-loader/AppNotAwaitable.tsx
=> chore: rename to available

client/packages/notification/components/NotificationBell.tsx
=> chore: fix NotificationBell circle size

backend/src/Equinor.ProjectExecutionPortal.Application/Equinor.ProjectExecutionPortal.Application.csproj, backend/src/Equinor.ProjectExecutionPortal.Infrastructure/Equinor.ProjectExecutionPortal.Infrastructure.csproj, backend/src/Equinor.ProjectExecutionPortal.WebApi/Equinor.ProjectExecutionPortal.WebApi.csproj, backend/src/tests/Equinor.ProjectExecutionPortal.Tests.WebApi/Equinor.ProjectExecutionPortal.Tests.WebApi.csproj
Specifically due to breaking change in Fusion libraries
=> chore: upgrade some nuget packages to latest

.github/workflows/dependabot.yml, backend/src/Equinor.ProjectExecutionPortal.sln
Adds dependabot to maintain packages
=> feat: add dependabot

clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Views/Shared/_Layout.cshtml
EDS is changing the url for its font, https://equinor.slack.com/archives/CJT20H1B9/p1680252024573529. 
This pr updates url
=> chore(eds): update eds url

client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx, client/packages/portal-core/src/providers/menu/MenuProvider.tsx, client/packages/portal-core/src/providers/menu/menu-types.ts
closes: https://github.com/equinor/lighthouse/issues/143
=> fix: :bug: Search result not erased from meny after launching an app

client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx, client/packages/portal-core/src/app-loader/uss-app-module.ts, client/packages/portal-pages/src/pages/project-page/components/favorites/Favorites.tsx
=> fix: :bug: fix cpu usage

backend/src/Equinor.ProjectExecutionPortal.Application/Queries/WorkSurface/GetWorkSurfaceAppGroupsWithContextAndGlobalApps/GetWorkSurfaceAppGroupsWithContextAndGlobalAppsQuery.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Queries/WorkSurface/GetWorkSurfaceAppGroupsWithGlobalApps/GetWorkSurfaceAppGroupsWithGlobalAppsQuery.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Services/AppService/AppService.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Services/WorkSurfaceService/IWorkSurfaceService.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Services/WorkSurfaceService/WorkSurfaceService.cs
Apps should be ordered by Name instead of Order.
Had to refactor a bit by updating mapping methods
https://github.com/equinor/lighthouse/issues/160
=> feat: apps should be ordered by Name instead of Order

backend/src/Equinor.ProjectExecutionPortal.Application/Services/WorkSurfaceService/WorkSurfaceService.cs
AppGroups should be sorted by Name, not Order
=> feat: appGroups should be sorted by Name, not Order

client/packages/portal-utils/src/menu-utils/utils.ts
(https://github.com/equinor/lighthouse/issues/160)
=> feat: :sparkles: alphabetical order in meny

backend/src/Equinor.ProjectExecutionPortal.Application/Commands/OnboardedApps/UpdateOnboardedApp/UpdateOnboardedAppCommand.cs, backend/src/Equinor.ProjectExecutionPortal.Domain/Entities/OnboardedApp.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/OnboardedAppController.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/OnboardedApp/ApiUpdateOnboardedAppRequest.cs, backend/src/tests/Equinor.ProjectExecutionPortal.Tests.WebApi/IntegrationTests/AppGroupControllerTests.cs, backend/src/tests/Equinor.ProjectExecutionPortal.Tests.WebApi/IntegrationTests/OnboardedAppControllerTests.cs
This feature makes it possible to update Onboarded Apps. The only field you are able to update is the App Group, thus making it possible to change this from the API.
=> feat: update onboarded app

.github/dependabot.yml
Automatically adds team as reviewers to Dependabot
=> chore: Automatically add team as reviewers to Dependabot

client/packages/portal-core/src/context-selector/ContextSelector.tsx, client/packages/portal-core/src/context-selector/PortalContextSelector.tsx, client/packages/portal-core/src/framework-configurator/portal-context-configurators.ts, client/packages/portal-core/src/hooks/index.ts, client/packages/portal-core/src/hooks/use-onboarded-contexts.ts, client/packages/portal-core/src/queries/hooks/index.ts, client/packages/portal-core/src/queries/hooks/use-onboarded-context-query.ts, client/packages/portal-core/src/queries/portal/getAvailableContexts.ts, client/packages/portal-core/src/types/onboarded-contexts.ts, client/packages/portal-pages/src/pages/project-page/ProjectPage.tsx, client/packages/portal-pages/src/pages/view-page/ViewContextAvailableDialog.tsx, client/packages/portal-pages/src/pages/view-page/ViewPage.Styles.ts, client/packages/portal-pages/src/pages/view-page/ViewPage.tsx
- When the user selectes a context that is not activated a dialog will appear saying hat the context is not available. 
- When clearin g context it wil be removed from local storage.
- No view error page
- This is reviewd by ux :)
=> feat: on context not available display dialog and remove selected context.

client/packages/portal-client/vite.config.ts, client/packages/portal-core/tsconfig.json
fix teh lagasy loader files so that they kan be deplyed
=> fix: update build config to move globalResources and appLegacyLoader to proper location

client/packages/portal-pages/src/pages/project-page/components/favorites/Favorites.tsx, client/packages/portal-pages/src/pages/project-page/hooks/use-favorites.ts
If application is not activated for the current context the button on the homepage is dissabled 
Closes: #292
=> fix: Fix favorites, apps are disabled when not active in context

client/packages/portal-client/package.json, client/packages/portal-client/vite.config.ts, clientBackend.Dockerfile
A bug occurred in local development the legacy apps was not working, had to add mode and check fot it in vite config to fix.
=> fix: vite build mode

clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Controllers/BundleController.cs
Disable cache for index page due to sometime outdated js client
=> Disable cache for index page due to sometime outdated js client

.github/issue_template.md
=> chore: update issue_template.md

README.md
Add build status badges from Radix in README
=> Add Radix build status badge to README

.github/workflows/client-pr.yml
=> chore: remove common action in client pr wf

legacyAppLoader/src/app-loader/legacy-interopt/components/LegacyFusionWrapper.tsx
=> fix: scrollbar in legacy apps

.github/workflows/update-lockfile.yml
=> chore(snyk): action to update lockfile on snyk PRs

.github/issue_template.md
=> chore: update Issu template with backen url's and dod

client/packages/portal-pages/src/pages/project-page/components/favorites/Favorites.tsx
=> fix: favorites links

radixconfig.yaml
added azure identity to radix config
=> feat: added azure identity to radix config

.github/workflows/backend-pr.yml
This should be updated to run test and other backend validations
=> fix: backend pr jobs

.changeset/pr-393-1542928735.md, .github/actions/create-changeset/dist/index.js, .github/actions/create-changeset/src/changeset.ts, .github/pull_request_template.md
Extending the changeset action to handle relations. For now this is only for database migration but more can be added in the future.
=> feat: add database migration information label to changeset

.changeset/pr-395-1543127205.md, .github/actions/create-changeset/dist/index.js, .github/actions/create-changeset/src/changeset.ts, .github/workflows/common-release.yml
Change will remove all comments in change set. This will enforce that developer needs wo write a change set if not `none` is checked.
=> chore: remove comments from changeset and improve change type regex

.changeset/pr-398-1544881918.md, .github/pull_request_template.md
Update pr templat with a linebreake
Update pr templat with a linebreake
=> chore: update pr template

.changeset/pr-397-1544878353.md, client/packages/portal-core/src/portal-actions/portal-actions-config.tsx
This pull request is for demo purpose and will include an incomplete feature that will be removed after demo.
This pull request is for demo purpose and will include an incomplete feature that will be removed after demo.
=> chore: add my account portal action option

.changeset/pr-417-1572406933.md, clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Modules/AssetProxyConfiguration.cs
> Add support for Fusion asset paths
Add support for Fusion asset paths
=> feat: update asset proxy url

.changeset/pr-431-1582188051.md, client/packages/portal-client/src/components/portal-frame/PortalFrame.tsx
Added bookmark resolve path missing / after app key 
Fixing bookmark resolve path for bookmark navigation
=> fix(bookmark): resolve path

.changeset/pr-439-1590685930.md, client/packages/components/src/components/my-account/MyAccount.tsx, client/packages/components/src/components/my-allocations-tab/MyAllocationTab.test.tsx, client/packages/components/src/components/my-allocations-tab/MyAllocationTab.tsx, client/packages/components/src/components/portal-settings-tab/PortalSettingsTab.tsx, client/packages/types/src/user/person-details.ts
added no content to allocations tab plus added test
The my allocations tab will now show no content message if no allocations are available
=> feat: added no content to allocations tab plus added test

.changeset/pr-451-1600739312.md, client/packages/components/src/components/help/Help.tsx
simplify language in help text
Revise help text for clarity and correct typos.
=> core: update help.tsx

.changeset/pr-467-1608707039.md, client/packages/notification/components/NotificationCard.tsx, client/packages/notification/components/adaptivCard/AdaptivCardViewer.tsx
fixing styles on button and enabled text overflow ellipsis...
Fixed Styles on Button in notification  and fixed text overflow, ensuring that text content within elements will gracefully truncate with an ellipsis (...) when exceeding the available space. This enhancement improves readability and maintains a polished interface.
=> fix: styling on notifications

.changeset/pr-461-1602619888.md, client/packages/portal-ui/src/task/work-assigned/Tasks.tsx, client/packages/portal-ui/src/task/work-assigned/WorkAssigned.tsx
fix double scrollbar in side sheet on my work assigned
Improved user experience by resolving the issue of a duplicated scrollbar in the side sheet on the assigned work page.
=> fix: double scrollbar in side sheet

.changeset/pr-495-1638958384.md, client/packages/portal-ui/src/header/breadcrumbs/AppBreadcrumb.tsx, client/packages/portal-ui/src/header/breadcrumbs/styles.ts
fixed focus on app breadcrumb now not focusing on last app
Fixed focus on app breadcrumb now not focusing on last app
=> fix: fixed focus on app breadcrumb

.changeset/pr-498-1640841928.md, client/packages/portal-pages/src/pages/project-page/components/project-cards/milestones/Milestones.tsx, client/packages/portal-pages/src/pages/project-page/components/project-cards/milestones/use-presence-query.ts, client/packages/portal-pages/src/pages/project-page/components/project-cards/milestones/utils.ts
sot milestones on project home page by date and milestone
Milestones on the project home  page are now sorted  by date and then by milestone title.
=> feat: sort milestones on project home page by date and milestone

.changeset/pr-488-1632401132.md, client/packages/service-message/components/ServiceMessage.tsx
Move the service message info to action bar in side sheet 
Move the service message info to action bar in side sheet.
=> chore: move info icon to action-bar in side-sheet

.changeset/pr-499-1644095816.md, client/packages/portal-client/src/lib/portal-framework-config.tsx, legacyAppLoader/app.config.js
provide proper client id for legacy applications
Providing proper client id for legacy applications. This to ensure propper loading of applications.
=> fix: provide proper client id for legacy applications

.changeset/pr-522-1684905759.md, client/packages/portal-client/src/lib/portal-framework-config.tsx, client/packages/portal-client/src/pages/AppPage/AppPage.tsx
fixing the landing of review and url handling for legacy applications
fixing the landing of review and url handling for legacy applications
=> fix: fix for review and url handling on legacy apps

.changeset/pr-526-1686345305.md, client/packages/components/src/components/task/Tasks.tsx
fix loading spinner on all my assignments
fix loading spinner on all my assignments
=> fix: my assignments loading when you have noe

.changeset/pr-585-1743329415.md, client/packages/portal-client/src/lib/feature-logger.ts, client/packages/portal-client/src/lib/portal-framework-config.tsx
Added feature logger class in setup that lisens on events on context hanged and application manifet changed.
Portal now integrates with the Fusion feature logging system, enhancing the visibility of logged applicaion and context selected in the Fusion User Statistics report.
=> feat: app and context logging against fusion

.changeset/pr-588-1754308665.md, client/packages/portal-pages/src/pages/project-page/components/InfoBox/InfoBox.tsx
scoping styling for info box
Scoping for landing page.
=> chore: scoping styling for info box

.changeset/pr-604-1774155564.md, backend/src/Equinor.ProjectExecutionPortal.WebApi/Program.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/appsettings.json, radixconfig.yaml
=> fix: add fusion enviroment variable

.changeset/pr-611-1783937277.md, radixconfig.yaml
=> azure identity true for prod

.changeset/pr-609-1777115383.md, client/packages/components/src/components/app-context-message/AppContextMessage.tsx, client/packages/components/src/index.ts, client/packages/core/src/modules/portal-config/hooks/use-favorites.ts, client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx, client/packages/portal-pages/src/pages/project-portal-page/ProjectPortalPage.tsx, client/packages/portal-pages/src/pages/sheared/components/AllApps.tsx, client/packages/ui/src/components/message/Message.tsx, radixconfig.yaml
App and Context expansion message.
=> feat: app context expansion message

.changeset/pr-647-1884331840.md, client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx
Fixed app sorting in project portal
Fixed app sorting in project portal
=> Fusion Project Portal Release (#632)

.changeset/pr-668-1953263076.md, backend/src/Equinor.ProjectExecutionPortal.Application/Commands/ContextTypes/AddContextType/AddContextTypeCommand.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Commands/ContextTypes/RemoveContextType/RemoveContextTypeCommand.cs, backend/src/Equinor.ProjectExecutionPortal.Application/Queries/ContextTypes/GetContextTypes/GetContextTypesQuery.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/ContextTypeController.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/ContextType/ApiAddContextTypeRequest.cs, backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/ContextType/ApiRemoveContextTypeRequest.cs
Possible to add  context types, so that they can be available for portals. 
CRUD for context type
=> feat: get post and delete to context-type

.changeset/pr-682-2005722119.md, clientBackend.Dockerfile
Change Node version for client build
=> fix: change node version to 20.1

.changeset/pr-685-2008088683.md, client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx
Fixing application list on smaler screens now with scrpollbar
Bug Fix: The application list in the menu now features a scrollbar for better usability on smaller screens.
=> fix: Make application list scrollable on smaller screens

.changeset/pr-686-2008093354.md, client/package.json
Updated styled-components to version 5.3.11 to prevent critical vulnerability
=> fix: :lock: Update styled-components to safe version

.changeset/pr-746-2073331715.md, clientBackend.Dockerfile
=> fix: install fusion cli in docker file

.changeset/pr-787-2090874541.md, backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/ProfileController.cs
Access admin check endpoint
Access admin check endpoint
=> Access admin check endpoint

.changeset/pr-790-2091101092.md, client/packages/portal-client/package.json
Release after build fail - old failing code removed
=> chore: prod trigger

.changeset/pr-792-2091178560.md, client/apps/portal-administration/src/pages/Portal.tsx
Poratl Administration - scrollbar on portal edit page
=> fix: scrollbar on portal edit page

.changeset/pr-795-2093365743.md, client/packages/portal-ui/src/style-provider/globalStyles.ts
fix side sheet height for apps now showing bottom 48 is pixels
Fixing side sheet height for apps.
=> fix: fixing side-sheet for apps

.changeset/pr-798-2093415812.md, client/packages/portal-core/src/hooks/use-context-resolver.ts
Add subTitle property to context items in useContextResolver hook
Add context type name displayed on all context search results
=> fix: Add subTitle property to context items in useContextResolver hook

.changeset/pr-801-2093607063.md, client/packages/portal-client/src/lib/portal-framework-config.tsx, client/packages/portal-pages/src/pages/project-page/Overview.tsx
Add milestones under feature flag default on
Add milestones under feature flag default on
=> chore: add milestones under feature flag default on

client/packages/portal-client/src/components/portal-side-sheet/PortalSideSheet.tsx
fix side sheet height on portal side-sheets.
fix side sheet height on portal side-sheets.
=> chore: update PortalSideSheet styles

.changeset/pr-821-2129413296.md, client/packages/components/src/components/task/hooks/use-assignment.ts, client/packages/components/src/components/task/queries/fusion-meetings-queries.ts
Update api version on meeting actions to the newest version.
=> chore: update api version on meetings actions

.changeset/pr-826-2137768494.md, client/packages/core/src/app/hooks/use-app-loader.ts
fix: providing the right env key to appLoader
providing the right env key to appLoader
=> fix: providing the right env key to appLoader

.changeset/pr-830-2140934096.md, client/packages/portal-client/src/components/service-message-filter/ServiceMessageFilter.tsx
Update key property in registerCurrentApps function call
Update key property in registerCurrentApps function call
=> refactor: Update key property in registerCurrentApps function call

.changeset/pr-839-2150926314.md, backend/src/Equinor.ProjectExecutionPortal.WebApi/Controllers/ProfileController.cs
Adds a profile controller with an endpoint for validating user permission on frontend
- Adds a profile controller with an endpoint for validating user permission on frontend
=> feat: add profile controller

.changeset/pr-842-2151222137.md, .github/actions/get-fusion-token/action.yml, .github/workflows/common-release.yml, .github/workflows/deploy-portal-administration-ci.yml
update portal admin app release actions for new fusion cli
update portal admin app release actions for new fusion cli
=> chore: update app release actions

.changeset/pr-846-2155757224.md, client/packages/portal-client/src/lib/portal-framework-config.tsx, client/packages/service-message/provider/ServiceMessageProvider.tsx, client/packages/service-message/query/use-service-message-query.ts
Description on migration is written here: https://github.com/equinor/fusion-rfcs/issues/82
Update url to  the service message service
=> chore(service-messages): migrate to new api and hub

.changeset/pr-858-2169275298.md, client/packages/components/src/components/my-allocations-tab/MyAllocationTab.test.tsx, client/packages/portal-client/src/portal.config.feature.json, client/packages/portal-client/src/portal.config.json, client/packages/utils/src/url/fusion-portal-url.ts
Update Fusion Portal URLs in codebase
#857
Update of all  Fusion Classic URLs in codebase
=> chore: Update Fusion Portal URLs in codebase

.changeset/pr-867-2189754879.md, .github/workflows/common-release.yml, client/apps/portal-administration/package.json
update Node.js version to 20 and bump portal-administration 1.0.4
Update piplenes for admin app and new admin app release
=> fix: update Node.js version to 20 and bump portal-administration 

backend/src/Equinor.ProjectExecutionPortal.WebApi/ViewModels/OnboardedApp/ApiOnboardAppRequest.cs, client/apps/portal-administration/src/components/OnboardedApps/AppsTable.tsx, client/apps/portal-administration/src/components/Portal/EditPortalForm.tsx
Fixing minor bugs in admin app
Fixing minor bugs in admin app:
- Display name in onboaded apps
- Refresh on portal save now working propperly
=> fix: admin app bugs

client/packages/portal-client/src/components/portal-router/Routes.tsx, client/packages/portal-client/vite.config.ts
update portal routes and change proxy target URL
update portal routes and change proxy target URL
=> fix: update portal routes and change proxy target URL

clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Controllers/BundleController.cs
Overrides /authentication url to redirect to index instead of another signin window. Results in one signin window and faster signin process
=> chore: fix bug where multiple sign-in prompts occur

clientBackend/src/Equinor.ProjectExecutionPortal.ClientBackend/Controllers/BundleController.cs
Fixed a bug where root route did override the SPA router
=> bug: removed root route that overrides the SPA router

client/packages/core/src/modules/portal-config/hooks/use-portal-config.ts, client/packages/core/src/modules/portal-config/portal.ts, client/packages/core/src/modules/portal-config/state/actions.ts, client/packages/core/src/modules/portal-config/state/create-reducer.ts, client/packages/portal-client/src/components/portal-menu/PortalMenu.tsx, client/packages/portal-client/src/lib/portal-framework-config.tsx
Fixing infinitt loading in menu and removes apps when no context selected
=> fix: add clearAppKeys action and loading state to portal hooks

.changeset/pr-884-2223392136.md, client/README.md
The release includes
- Add clearAppKeys action and loading state to portal hooks
- Disable response caching
- fix bug where multiple sign-in prompts occur
- update portal routes and change proxy target URL
=> realese: minor

.changeset/pr-893-2230942484.md, client/packages/core/src/modules/portal-apps/portal-apps-client.ts
update API endpoints for app keys to apps in PortalAppsClient
=> fix: update API endpoints for app keys to apps in PortalAppsClient

.changeset/pr-904-2261554183.md, client/apps/legacyAppLoader/app.config.ts, client/packages/core/src/app/utils/app-get-legacy-client-config.ts
=> chore: update fusion ci urls

.changeset/pr-907-2263833125.md, client/packages/portal-client/src/lib/portal-framework-config.tsx
Update SignalR hub path for servicemessages
Update SignalR hub path for servicemessages
=> chore: Update SignalR hub path for servicemessages

.changeset/pr-909-2283732642.md, client/packages/components/src/components/app-search/AppSearchBar.tsx
Update subtitle to use displayName instead of name
=> fix: update subtitle to use displayName instead of name

.changeset/pr-920-2428249778.md, client/packages/portal-client/index.html
=> fix: update page title from 'Fusion' to 'Project Portal'

client/packages/portal-client/index.html, clientBackend.Dockerfile
Fix build, assets are no longe present in build
=> Fix  not coppy assets

.changeset/pr-927-2450280354.md, client/packages/service-message/components/ServiceMessage.tsx
Remove unnecessary messages for apps that are not active in portal
=> fix: remove unnecessary messages for apps that are not active in portal

.changeset/pr-936-2566699585.md, client/package.json, client/yarn.lock
Added the ability to copy bookmarks to the clipboard in the bookmark component when bookmark is shared with the user. This allows users to easily share bookmarks with others by copying the bookmark link to their clipboard.
=> chore: update fusion framework bookmark to latest versions

.changeset/pr-940-2568151443.md, client/packages/portal-client/src/lib/bookmark-init.ts, client/packages/portal-client/src/lib/portal-framework-config.tsx
add bookmark initialization and update portal framework configuration
=> chore: add bookmark initialization and update portal framework configuration
